apiVersion: v1
kind: Service
metadata:
  name: auctionapp-svc
  labels:
    app: auctionapp
spec:
  type: NodePort
  selector:
    app: auctionapp
  ports:
    - port: 50
      targetPort: 50
      nodePort: 31007
